name: windows

on:
  workflow_dispatch:
  push:
    paths:
      - '**'
      - '!.github/**'
      - '!**.yml'
      - '.github/workflows/windows.yml'
      - '!**.md'
      - '!.vscode/**'
      - '!doc/**'

  pull_request:
    paths:
      - '**'
      - '!.github/**'
      - '!**.yml'
      - '.github/workflows/windows.yml'
      - '!**.md'
      - '!.vscode/**'
      - '!doc/**'

jobs:
  windows:
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v6
      with:
        submodules: recursive

    - name: cmake --version
      run: cmake --version

    - name: build stratagus
      run: | # -DENABLE_NSIS=ON
        mkdir build && cd build
        cmake .. -DCMAKE_BUILD_TYPE=Release -DBUILD_VENDORED_LUA=ON -DBUILD_VENDORED_SDL=ON -DBUILD_VENDORED_MEDIA_LIBS=ON -DENABLE_STDIO_REDIRECT=ON -DBUILD_TESTING=1 -DCMAKE_POLICY_VERSION_MINIMUM=3.5
        cmake --build . --config Release
        
    - name: run tests
      run: |
        cd build
        ctest --output-on-failure

    - name: Upload installer
      uses: actions/upload-artifact@v6
      with:
        name: stratagus
        path: build/Release/**.*

#    - name: Upload installer
#      uses: actions/upload-artifact@v6
#      with:
#        name: stratagus-installer.exe
#        path: build/**.exe
#
#    - name: Upload pdb files
#      uses: actions/upload-artifact@v6
#      with:
#        name: stratagus_pdbs
#        path: "**.pdb"
